**Numpy**

NumPy es una biblioteca para el lenguaje de programación Python, que agrega soporte para arreglos y matrices grandes y multidimensionales, junto con una gran colección de funciones matemáticas de alto nivel para operar en estos arreglos.

Sitio web:
[https://numpy.org/](https://numpy.org/)


En este notebook trabajaremos los conceptos básicos de numpy y algunas características del lenguaje Python en el ambiente de trabajo Colab 

In [1]:
import numpy as np

Python maneja de las sentencias de control usando sangrías

In [2]:
for i in range(10):
    print(i) #Comando dentro del for
j=2*i # Comando fuera del for
print(j)



0
1
2
3
4
5
6
7
8
9
18


Creación de vectores con numpy

In [3]:
a=np.array([1,2,5])
print(a)

[1 2 5]


In [4]:
b=np.array(range(5))
print(b)

[0 1 2 3 4]


Acceso a los elementos de un vector. En Python para acceder al el primer elemento se usa el índice cero

In [5]:
print(a[0]) # Primer elemento 

1


In [6]:
print(b[3]) # Cuarto elemento 

3


In [7]:
print(b[-1]) # Acceso al último componente del vector

4


In [8]:
print(b[-2]) # Acceso al penúltimo componente del vector

3


In [9]:
print(b[1:4]) #Accediendo a varios elementos de un vector

[1 2 3]


Conociendo las dimensiones de un vector o arreglo

In [10]:
print(b.shape)

(5,)


Redimensionando vectores en Python. Los vectores son arreglos de una dimensión.
Para trabajar "vectores" fila y columna en Python hay que especificar dos dimensiones, es decir que técnicamente son matrices

In [11]:
bfila=b.reshape(1,5)  #Vector fila
print(bfila.shape)

(1, 5)


In [12]:
bcol=b.reshape(5,1) #Vector columna
print(bcol.shape)

(5, 1)


Creación de una matriz

In [13]:
b=np.array([(1,2,3),(4,5,6)])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [14]:
c=np.array([(7,8,9),(10,11,12)])
print(c)
print(c.shape)

[[ 7  8  9]
 [10 11 12]]
(2, 3)


Concatenando matrices de manera vertical

In [15]:
e=np.vstack((b,c))
print(e)
print(e.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


Concatenando matrices de manera horizontal

In [16]:
e2=np.hstack((b,c))
print(e2)
print(e2.shape)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
(2, 6)


Creación de un arreglo cúbico a partir de dos matrices

In [17]:
f = np.array((b,c))
print(f)
print(f.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


Creación de arreglos multidimensioanles

In [18]:
a=np.zeros((10,32,32,3))
b=np.zeros((10,32,32,3))
c=np.vstack((a,b))
print(c.shape)
d = np.array((a,b))
print(d.shape)

(20, 32, 32, 3)
(2, 10, 32, 32, 3)
